# Generated by Django 5.0.1 on 2024-02-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_likers_comment_likes_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_number',
        ),
    ]
