# Generated by Django 5.0.1 on 2024-02-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_age'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(related_name='users', to='categories.category'),
        ),
    ]
