# Generated by Django 5.0.1 on 2024-02-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='is_email_verified',
        ),
    ]
