# Generated by Django 5.0.1 on 2024-02-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('language', models.CharField(blank=True, max_length=15, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('publish_date', models.DateField(null=True)),
                ('ratings_number', models.IntegerField(blank=True, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('categories', models.ManyToManyField(related_name='books', to='categories.category')),
            ],
        ),
    ]
